enum AccountType {
  LOGIN = '/ACCOUNT/LOGIN',
  GET_LOGIN_TOKEN = '/ACCOUNT/GET_LOGIN_TOKEN',
  SET_LOGIN_TOKEN = '/ACCOUNT/SET_LOGIN_TOKEN',
  DELIETE_LOGIN_TOKEN = '/ACCOUNT/DELIETE_LOGIN_TOKEN',
  REGISTER = '/ACCOUNT/REGISTER',
  UNREGISTER = '/ACCOUNT/UNREGISTER'
}

export default AccountType;
